[package]
name = "arrata-quirks"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
serde_yaml = "0.9.34"
toml = "0.8.19"

[dependencies.arrata-lib]
git = "https://github.com/Arrata-TTRPG/Arrata-LIB"
branch = "main"
